defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  host: localhost

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *defaults
  database: encubo_test

production:
  <<: *defaults
  database: encubo_production
