defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password: mysqlG@llo
  host: localhost

development:
  <<: *defaults
  database: encubo_development

test:
  <<: *defaults
  database: encubo_test

production:
  <<: *defaults
  database: encubo_production
