defaults: &defaults
  adapter: mysql2
  username: root
  password:
  host: localhost

development:
  <<: *defaults
  database: encubo_development

test:
  <<: *defaults
  database: encubo_test

productiont:
  <<: *defaults
  database: encubo_production
